sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lasse1900/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lasse1900/docker-react npm run test
